// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkhajrcmvkiamqpiazzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdraGFqcmNtdmtpYW1xcGlhenp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MzY0NTMsImV4cCI6MjA2ODMxMjQ1M30.d97opPuAqlddUkeXM_-kj1ZdUu8q82CaIsqmYHa8i00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});